name: CI/CD Pipeline for Artifact Registry and Cloud Run

on: 
  push: 
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3 

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/fastapi-repo/fastapi-repo:latest .

    - name: Check Artifact Registry repository
      id: check_repo
      run: |
        REPO_NAME="fastapi-repo"
        REGION="us-central1"
        PROJECT_ID="${{ secrets.GCP_PROJECT }}"

        if gcloud artifacts repositories describe "$REPO_NAME" \
            --location="$REGION" \
            --project="$PROJECT_ID" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✅ Artifact Registry exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "❌ Artifact Registry '$REPO_NAME' not found in $REGION"
          exit 1
        fi

    - name: Push Docker image to Artifact Registry
      if: steps.check_repo.outputs.exists == 'true'
      run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/fastapi-repo/fastapi-repo:latest

    - name: Check Cloud Run service
      id: check_service
      run: |
        SERVICE_NAME="fastapi-service"
        REGION="us-central1"
        PROJECT_ID="${{ secrets.GCP_PROJECT }}"

        if gcloud run services describe "$SERVICE_NAME" \
            --region "$REGION" \
            --project "$PROJECT_ID" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✅ Cloud Run service exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "❌ Cloud Run service '$SERVICE_NAME' not found in $REGION"
          exit 1
        fi

    - name: Deploy new revision
      run: |
        gcloud run deploy fastapi-service \
          --image "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/fastapi-repo/fastapi-repo:latest" \
          --region us-central1 \
          --platform managed \
          --port 8000 \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT }} \
          --quiet

    # - name: Publish CI/CD Event to Pub/Sub
    #   if: always()
    #   run: |
    #     STATUS="success"
    #     if [ "${{ job.status }}" != "success" ]; then
    #       STATUS="failure"
    #     fi

    #     gcloud pubsub topics publish ci-cd-events \
    #       --message="{\"status\":\"$STATUS\",\"commit\":\"${GITHUB_SHA}\",\"repo\":\"${GITHUB_REPOSITORY}\", \"run_id\": \"${GITHUB_RUN_ID}\"}" \
    #       --project=${{ secrets.GCP_PROJECT }}
    #   env:
    #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        